### ISSUE TITLE
Составить интро

### ISSUE THREAD

**Issue by YashaBlendeer** [YashaBlendeer/homepage#4]
Составить интро (вступление), где в 2-4 предложениях описать, что заказчик делает, что нравится делать, что хочется делать лучше, что важно делать, и т.д.

**Comment by SavaDoppelganger** [comment]
**Данте Спардович (Dante/ダンテ)**
_― Мне пришлось съесть пиццу за пять минут. Это мой новый личный рекорд._
Охотник на демонов. Любитель пиццы и клубничного сандэ. Заботливый брат и дядя.
