### ISSUE TITLE
Составить блок контактной информации

### ISSUE THREAD

**Issue by YashaBlendeer** [YashaBlendeer/homepage#5]
Ссылки на соцсети (Facebook или Instagram, и т.п.), номер телефона или адрес электронной почты, т.п. Может не все ссылки в мире, а только те, которые действительно уместны.

**Comment by SavaDoppelganger** [comment]
Dante`s contacts
•	shittyuncle@gmail.com
•	https://twitter.com/devilmaycry
•	https://www.instagram.com/devilmaycry_fanpage/
