### ISSUE TITLE
Составить дополнительные информационные блоки

### ISSUE THREAD

**Issue by YashaBlendeer** [YashaBlendeer/homepage#7]
Можно сделать резюме менее формальным, добавив дополнительные блоки, которые содержат полезную информацию, но подают её в "развлекательной" форме. Например, что нравится и не нравится, сильные и слабые стороны, перечень навыков или хобби, инфографика или же интерактивные модули, и т.п. Стоит написать контент такого блока раньше, чем начинать верстку, потому что его размеры будут влиять на размещение элементов на странице.

**Comment by SavaDoppelganger** [comment]
**ЖИЗНЬ & УЧЕБА**
Образование от мамы, сила от папы, шишки на голове – от старшего брата.
**ЯЗЫКИ**
🇺🇸 ENGLISH ru RUSSIAN 🇯🇵 JAPANESE
**СПОСОБНОСТИ & ОРУЖИЕ** 
Являясь полудемоном-получеловеком обладаю огромной силой. Могу рушить твердые поверхности, например камни, без особых усилий. 
Ослепительно быстрый. Маневренность позволяет совершать удивительные акробатические трюки, которые не может превзойти даже самый лучший человек-акробат. 
Могу мгновенно исцелить почти любую рану.  
Devil Trigger позволяет выпускать наружу мою демоническую силу.
Использую пистолеты Эбони и Айвори, меч Мятежник и дробовик. А если нахожу какое-то новое оружие, то забираю его себе.
**НРАВИТСЯ 😃**
ПИЦЦА КЛУБНИЧНОЕ САНДЭ GETTING THIS PARTY CRAZY БРАТ ПЛЕМЯННИК БИТВЫ
**НЕПРИЯЗНЬ 😞**
ОЛИВКИ НЕРАБОЧАЯ МАГНИТОЛА ВЫХОДКИ БРАТА
**ХОЧУ 🥺**
ОПЛАТИТЬ ДОЛГИ ВЫЙТИ ИЗ ПОДЗЕМНОГО МИРА
